name: LeaderPrefix
version: "${project.version}"
main: net.earthmc.leaderprefix.LeaderPrefix
api-version: "1.19"
depend: [Towny, PlaceholderAPI]
authors: [Fruitloopins]
description: Allow nation leaders to switch between a K or Q prefix
website: https://earthmc.net
